kind: Secret
apiVersion: v1
metadata:
  name: {{ include "postgres15.name" . }}
  labels:
    {{- include "postgres15.labels" . | nindent 4 }}
stringData:
  database-user: {{ .Values.pgsql.user }}
  database-password: {{ .Values.pgsql.password }}
  database-name: {{ .Values.pgsql.database }}
  database-admin-password: {{ include "postgres15.admin-password" . }}
type: Opaque
