kind: ResourceQuota
apiVersion: v1
metadata:
  name: storage
spec:
  {{- if eq .Values.namespace.size "small" }}
  {{- toYaml .Values.small.resourcequotas.storage | nindent 2 }}
  {{- end }}
  {{- if eq .Values.namespace.size "medium" }}
  {{- toYaml .Values.medium.resourcequotas.storage | nindent 2 }}
  {{- end }}
  {{- if eq .Values.namespace.size "large" }}
  {{- toYaml .Values.large.resourcequotas.storage | nindent 2 }}
  {{- end }}
