kind: ResourceQuota
apiVersion: v1
metadata:
  name: compute-deploy
spec:
  {{- if eq .Values.namespace.size "small" }}
  {{- toYaml .Values.small.resourcequotas.deploy | nindent 2 }}
  {{- end }}
  {{- if eq .Values.namespace.size "medium" }}
  {{- toYaml .Values.medium.resourcequotas.deploy | nindent 2 }}
  {{- end }}
  {{- if eq .Values.namespace.size "large" }}
  {{- toYaml .Values.large.resourcequotas.deploy | nindent 2 }}
  {{- end }}
