nameOverride: ""

openshift:
  user:
    name: 
    role: 

resourcequotas:
  deploy:
    hard:
      limits.cpu: '2'
      limits.memory: 8Gi
      requests.cpu: '1'
      requests.memory: 8Gi
    scopes:
      - NotTerminating
  build:
    hard:
      limits.cpu: '2'
      limits.memory: 8Gi
      requests.cpu: '1'
      requests.memory: 8Gi
    scopes:
      - Terminating
  storage:
    hard:
      count/persistentvolumeclaims: '5'
      limits.ephemeral-storage: 15Gi
      requests.ephemeral-storage: 15Gi
      requests.storage: 60Gi

limitranges:
  limits:
    - type: Container
      default:
        cpu: '1'
        memory: 1000Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi