---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.openshift.user.name }}-{{ .Values.openshift.user.role }}
subjects:
- kind: User
  name: {{ .Values.openshift.user.name }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Values.openshift.user.role }}
  apiGroup: rbac.authorization.k8s.io
